spring:
  application:
    name: configServer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\USER\Desktop\myClassDemo\micro-service\configServer\src\main\resources\config
          #外部資料夾--->本基開發使用
          #search-locations: classpath:/config
          #去 resources/config/ 底下找設定檔
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8888